INFO:     Will watch for changes in these directories: ['/home/dzoan/demo-library']
INFO:     Uvicorn running on http://0.0.0.0:8090 (Press CTRL+C to quit)
INFO:     Started reloader process [6897] using WatchFiles
/home/dzoan/demo-library/services/api/.venv/lib/python3.10/site-packages/pydantic/_internal/_fields.py:201: UserWarning: Field name "schema_json" in "Body_run_agent_v1_agents__agent_name__run_post" shadows an attribute in parent "BaseModel"
  warnings.warn(
INFO:     Started server process [6900]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:33646 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:33646 - "GET /openapi.json HTTP/1.1" 200 OK
/home/dzoan/demo-library/services/api/.venv/lib/python3.10/site-packages/shap/explainers/_tree.py:448: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn('LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray')
[run_457e81d5e27346e4a6bfc0e4e8e8923e] loading agent...
[run_457e81d5e27346e4a6bfc0e4e8e8923e] executing agent...
[narrative/ollama] failed: 404 Client Error: Not Found for url: http://localhost:11434/api/generate
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[narrative/ollama] failed: 404 Client Error: Not Found for url: http://localhost:11434/api/generate
INFO:     127.0.0.1:33660 - "POST /v1/agents/credit_appraisal/run HTTP/1.1" 200 OK
/home/dzoan/demo-library/services/api/.venv/lib/python3.10/site-packages/shap/explainers/_tree.py:448: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn('LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray')
[run_5f51fa38f24d4683b88c2ea7c7137a9a] loading agent...
[run_5f51fa38f24d4683b88c2ea7c7137a9a] executing agent...
[narrative/ollama] failed: 404 Client Error: Not Found for url: http://localhost:11434/api/generate
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[narrative/ollama] failed: 404 Client Error: Not Found for url: http://localhost:11434/api/generate
INFO:     127.0.0.1:47628 - "POST /v1/agents/credit_appraisal/run HTTP/1.1" 200 OK
INFO:     127.0.0.1:47634 - "GET /v1/runs/run_5f51fa38f24d4683b88c2ea7c7137a9a/report?format=pdf HTTP/1.1" 200 OK
INFO:     127.0.0.1:47646 - "GET /v1/runs/run_5f51fa38f24d4683b88c2ea7c7137a9a/report?format=scores_csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:47654 - "GET /v1/runs/run_5f51fa38f24d4683b88c2ea7c7137a9a/report?format=explanations_csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:47658 - "GET /v1/runs/run_5f51fa38f24d4683b88c2ea7c7137a9a/report?format=csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:47664 - "GET /v1/runs/run_5f51fa38f24d4683b88c2ea7c7137a9a/report?format=json HTTP/1.1" 200 OK
INFO:     127.0.0.1:57894 - "GET /v1/runs/run_5f51fa38f24d4683b88c2ea7c7137a9a/report?format=pdf HTTP/1.1" 200 OK
INFO:     127.0.0.1:57896 - "GET /v1/runs/run_5f51fa38f24d4683b88c2ea7c7137a9a/report?format=scores_csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:57898 - "GET /v1/runs/run_5f51fa38f24d4683b88c2ea7c7137a9a/report?format=explanations_csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:57910 - "GET /v1/runs/run_5f51fa38f24d4683b88c2ea7c7137a9a/report?format=csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:57924 - "GET /v1/runs/run_5f51fa38f24d4683b88c2ea7c7137a9a/report?format=json HTTP/1.1" 200 OK
/home/dzoan/demo-library/services/api/.venv/lib/python3.10/site-packages/shap/explainers/_tree.py:448: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn('LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray')
[run_357c54eba7a646c78c8f7674dc7370a6] loading agent...
[run_357c54eba7a646c78c8f7674dc7370a6] executing agent...
[narrative/ollama] failed: 404 Client Error: Not Found for url: http://localhost:11434/api/generate
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[narrative/ollama] failed: 404 Client Error: Not Found for url: http://localhost:11434/api/generate
INFO:     127.0.0.1:57930 - "POST /v1/agents/credit_appraisal/run HTTP/1.1" 200 OK
INFO:     127.0.0.1:57940 - "GET /v1/runs/run_357c54eba7a646c78c8f7674dc7370a6/report?format=pdf HTTP/1.1" 200 OK
INFO:     127.0.0.1:57954 - "GET /v1/runs/run_357c54eba7a646c78c8f7674dc7370a6/report?format=scores_csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:57966 - "GET /v1/runs/run_357c54eba7a646c78c8f7674dc7370a6/report?format=explanations_csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:57976 - "GET /v1/runs/run_357c54eba7a646c78c8f7674dc7370a6/report?format=csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:57978 - "GET /v1/runs/run_357c54eba7a646c78c8f7674dc7370a6/report?format=json HTTP/1.1" 200 OK
INFO:     127.0.0.1:39152 - "GET /v1/runs/run_457e81d5e27346e4a6bfc0e4e8e8923e/report?format=csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:54526 - "GET /v1/runs/run_457e81d5e27346e4a6bfc0e4e8e8923e/report?format=csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:54528 - "GET /v1/runs/run_457e81d5e27346e4a6bfc0e4e8e8923e HTTP/1.1" 200 OK
WARNING:  WatchFiles detected changes in 'services/ui/app.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [6900]
/home/dzoan/demo-library/services/api/.venv/lib/python3.10/site-packages/pydantic/_internal/_fields.py:201: UserWarning: Field name "schema_json" in "Body_run_agent_v1_agents__agent_name__run_post" shadows an attribute in parent "BaseModel"
  warnings.warn(
INFO:     Started server process [7033]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
/home/dzoan/demo-library/services/api/.venv/lib/python3.10/site-packages/shap/explainers/_tree.py:448: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn('LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray')
[run_178a42ddfcc34df4be99c6a80aa0ab9d] loading agent...
[run_178a42ddfcc34df4be99c6a80aa0ab9d] executing agent...
[narrative/ollama] failed: 404 Client Error: Not Found for url: http://localhost:11434/api/generate
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[narrative/ollama] failed: 404 Client Error: Not Found for url: http://localhost:11434/api/generate
INFO:     127.0.0.1:43420 - "POST /v1/agents/credit_appraisal/run HTTP/1.1" 200 OK
INFO:     127.0.0.1:43430 - "GET /v1/runs/run_178a42ddfcc34df4be99c6a80aa0ab9d/report?format=pdf HTTP/1.1" 200 OK
INFO:     127.0.0.1:43446 - "GET /v1/runs/run_178a42ddfcc34df4be99c6a80aa0ab9d/report?format=scores_csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:43460 - "GET /v1/runs/run_178a42ddfcc34df4be99c6a80aa0ab9d/report?format=explanations_csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:43474 - "GET /v1/runs/run_178a42ddfcc34df4be99c6a80aa0ab9d/report?format=csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:43476 - "GET /v1/runs/run_178a42ddfcc34df4be99c6a80aa0ab9d/report?format=json HTTP/1.1" 200 OK
WARNING:  WatchFiles detected changes in 'services/ui/app.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [7033]
/home/dzoan/demo-library/services/api/.venv/lib/python3.10/site-packages/pydantic/_internal/_fields.py:201: UserWarning: Field name "schema_json" in "Body_run_agent_v1_agents__agent_name__run_post" shadows an attribute in parent "BaseModel"
  warnings.warn(
INFO:     Started server process [7171]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:53240 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:53252 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:53252 - "GET /openapi.json HTTP/1.1" 200 OK
/home/dzoan/demo-library/services/api/.venv/lib/python3.10/site-packages/shap/explainers/_tree.py:448: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn('LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray')
[run_4f914b625f4e48ad85e6535377469a17] loading agent...
[run_4f914b625f4e48ad85e6535377469a17] executing agent...
[narrative/ollama] failed: 404 Client Error: Not Found for url: http://localhost:11434/api/generate
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[narrative/ollama] failed: 404 Client Error: Not Found for url: http://localhost:11434/api/generate
INFO:     127.0.0.1:43080 - "POST /v1/agents/credit_appraisal/run HTTP/1.1" 200 OK
INFO:     127.0.0.1:43082 - "GET /v1/runs/run_4f914b625f4e48ad85e6535377469a17%22/report?format=pdf HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:37520 - "GET /v1/runs/run_4f914b625f4e48ad85e6535377469a17%22/report?format=scores_csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:37522 - "GET /v1/runs/run_4f914b625f4e48ad85e6535377469a17/report?format=scores_csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:37522 - "GET /v1/runs/run_4f914b625f4e48ad85e6535377469a17/report?format=scores_csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:52424 - "GET /v1/runs/run_4f914b625f4e48ad85e6535377469a17/report?format=pdf HTTP/1.1" 200 OK
INFO:     127.0.0.1:52430 - "GET /v1/runs/run_4f914b625f4e48ad85e6535377469a17/report?format=scores_csv HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:42620 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:42620 - "GET /openapi.json HTTP/1.1" 200 OK
